version: '3'
services:
  ws:
    container_name: ws
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./app:/app
    depends_on:
      - was

  was:
    container_name: was
    build: ./php
    ports:
      - 9000:9000
    volumes:
      - ./app:/app
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: camagru
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db

  db:
    container_name: db
    build: ./mysql
    expose:
      - 3306
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: camagru
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  db-admin:
    container_name: db-admin
    image: phpmyadmin:latest
    ports:
      - 3306:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db

volumes:
  data:
